export const BASE_ROLE_ADMIN = 1;
export const BASE_ROLE_STAFF = 2;
export const BASE_ROLE_CUSTOMER = 3;

export const BASE_STATUS_ACTIVE = 1;
export const BASE_STATUS_INACTIVE = 0;

export const BASE_PAYMENT_STATUS_PENDING = 1;
export const BASE_PAYMENT_STATUS_PROCESSING = 2;
export const BASE_PAYMENT_STATUS_COMPLETED = 3;
export const BASE_PAYMENT_STATUS_FAILED = 4;
export const BASE_PAYMENT_STATUS_CANCELLED = 5;

export const BASE_CART_STATUS_OPEN = 1;
export const BASE_CART_STATUS_CHECKED_OUT = 2;
export const BASE_CART_STATUS_CANCELLED = 3;

export const BASE_ORDER_STATUS_PENDING = 1;
export const BASE_ORDER_STATUS_PROCESSING = 2;
export const BASE_ORDER_STATUS_SHIPPED = 3;
export const BASE_ORDER_STATUS_DELIVERED = 4;
export const BASE_ORDER_STATUS_CANCELLED = 5;
export const BASE_ORDER_STATUS_RETURNED = 6;
export const BASE_ORDER_STATUS_COMPLETED = 7;

export const BASE_PRODUCT_AVAILABILITY_IN_STOCK = 1;
export const BASE_PRODUCT_AVAILABILITY_OUT_OF_STOCK = 2;
export const BASE_PRODUCT_AVAILABILITY_PREORDER = 3;

export const BASE_USER_VERIFICATION_VERIFIED = 1;
export const BASE_USER_VERIFICATION_UNVERIFIED = 0;

export const BASE_LICENSES_STATUS_AVAILABLE = 1;
export const BASE_LICENSES_STATUS_SOLD = 2;
export const BASE_LICENSES_STATUS_ACTIVATED = 3;
export const BASE_LICENSES_STATUS_DEACTIVATED = 4;

export const BASE_METHOD_PAYMENT_EWALET_TRANSFER = 1;
export const BASE_METHOD_PAYMENT_BANK_TRANSFER = 2;
export const BASE_METHOD_PAYMENT_CASH = 3;
