const BASE_ROLE_ADMIN = 1;
const BASE_ROLE_STAFF = 2;
const BASE_ROLE_CUSTOMER = 3;

const BASE_STATUS_ACTIVE = 1;
const BASE_STATUS_INACTIVE = 0;

const BASE_PAYMENT_STATUS_PENDING = 1;
const BASE_PAYMENT_STATUS_COMPLETED = 2;
const BASE_PAYMENT_STATUS_FAILED = 3;
